- type: entity
  id: CEPipeBase
  categories: [ ForkFiltered ]
  abstract: true
  components:
  - type: Clickable
  - type: Transform
    anchored: true
    noRot: true
    # TODO: Remove both of these, same with CollideOnAnchor
  - type: Physics
    bodyType: Static
  - type: Appearance
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Metallic
  - type: CEPipeVis
    node: power
